typography_spectrum: 0.02599
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#6d6e72'
    - '#a8a9ad'
    - '#c0c1c2'
    - '#e7e7e8'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4bb1e77c-4311-431f-bfa0-2244b018512e.jpg
name: Ation Labs
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: d675ba5e-a82b-42af-ad44-fbd8bfe65694
    type: content
  - name: Skylar
    id: f4665194-a762-4a41-a364-c419ef073f67
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8018b355-ada2-4765-a8e7-0c1f5d2d7034.ico
title: Ation Labs
description: it ends with ation
purpose: []
