typography_spectrum: 0.9532927686814219
color:
  brandColors:
    - '#ffffff'
    - '#6d6e72'
    - '#a8a9ad'
    - '#c0c1c2'
    - '#e7e7e8'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.46149446559138596
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Ation Labs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ation Labs Corp
purpose: []
