name: ation labs
favicon: null
layout_spectrum: 0.2516891807317734
typography_spectrum: 0.9532927686814219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.664145230781287
  lightness: 0.684718778822571
  saturation: 0.46149446559138596
  rhythmicContrast: 0.7956826845183969
purpose: []
